version: "3"

includes:
  tests: "./taskfiles/tests.yaml"
  lint: "./taskfiles/lint.yaml"
  utils: "exports/taskfiles/utils/utils.yaml"

set: ["u", "pipefail"]
shopt: ["globstar"]

vars:
  G_OUTPUT_DIR: "{{.ROOT_DIR}}/build"
  # ugly aliases
  G_CPP_SRC_DIR: "taskfiles"
  G_BUILD_DIR: "{{.G_OUTPUT_DIR}}"
  ROOT_PATHS: ["{{.ROOT_DIR}}"]

tasks:
  clean:
    cmds:
      - "rm -rf '{{.G_OUTPUT_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_OUTPUT_DIR}}'"

  test:
    cmds:
      - task: "tests:all"
